name: MultiplePiglets
version: 1.2
main: me.lesxmore.multiplepiglets.MultiplePiglets
api-version: 1.19
load: STARTUP
authors: [lesxmore]
description: When breeding, pigs spawn multiple piglets at once. [Mobs]
commands:
  multiplepigletsreload:
    description: Reloads the MultiplePiglets configuration file
    usage: /multiplepigletsreload
